# Generated by Django 4.2.1 on 2023-11-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='profile_picture',
            field=models.ImageField(default='default_profile_picture.jpg', upload_to='profile_pictures/'),
        ),
    ]
