# Generated by Django 4.2.1 on 2023-11-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_friend_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_sent',
            field=models.BooleanField(default=True),
        ),
    ]
